In [30]:
'''
* Diabetes.csv를 사용하여 DecisionTree를 사용하여 
accuracy_score,metrics.precision_score, metrics.recall_score을 구하시오.


* 다음 데이터셋을 이용하여 VotingClassifier사용하여 
정확도를 구하시오.

from pydataset import data
df = data('Housing')

=> 다음의 Classfiters등을 사용함.
lr = LogisticRegression()
knn = KNeighborsClassifier()
dt = DecisionTreeClassifier()
'''

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import neighbors
from sklearn import datasets
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.ensemble import VotingClassifier

In [5]:
data=pd.read_csv("Diabetes.csv")
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [6]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1:].values.reshape(-1,1)
x,y

(array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
        [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
        [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
        ...,
        [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
        [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
        [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]]),
 array([[1],
        [0],
        [1],
        [0],
        [1],
        [0],
        [1],
        [0],
        [1],
        [1],
        [0],
        [1],
        [0],
        [1],
        [1],
        [1],
        [1],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [1],
        [1],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [0],
        [0],
        [0],
        [1],

In [8]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.3, random_state=0)

In [10]:
DT=DecisionTreeClassifier()
DT.fit(xtrain, ytrain)
DResult=DT.predict(xtest)
metrics.accuracy_score(ytest,DResult),metrics.precision_score(ytest,DResult),metrics.recall_score(ytest,DResult)

(0.7532467532467533, 0.6103896103896104, 0.6351351351351351)

In [11]:
data2=pd.read_csv("Housing.csv")
data2.head()

Unnamed: 0    price  lotsize  bedrooms  bathrms  stories driveway recroom  \
0           1  42000.0     5850         3        1        2      yes      no   
1           2  38500.0     4000         2        1        1      yes      no   
2           3  49500.0     3060         3        1        1      yes      no   
3           4  60500.0     6650         3        1        2      yes     yes   
4           5  61000.0     6360         2        1        1      yes      no   

  fullbase gashw airco  garagepl prefarea  
0      yes    no    no         1       no  
1       no    no    no         0       no  
2       no    no    no         0       no  
3       no    no    no         0       no  
4       no    no    no         0       no

In [13]:
data2['driveway'],class_names=pd.factorize(data2['driveway'])
data2['recroom'],_=pd.factorize(data2['recroom'])
data2['fullbase'],_=pd.factorize(data2['fullbase'])
data2['gashw'],_=pd.factorize(data2['gashw'])
data2['airco'],_=pd.factorize(data2['airco'])
data2['prefarea'],_=pd.factorize(data2['prefarea'])

In [14]:
data2.head()

Unnamed: 0    price  lotsize  bedrooms  bathrms  stories  driveway  \
0           1  42000.0     5850         3        1        2         0   
1           2  38500.0     4000         2        1        1         0   
2           3  49500.0     3060         3        1        1         0   
3           4  60500.0     6650         3        1        2         0   
4           5  61000.0     6360         2        1        1         0   

   recroom  fullbase  gashw  airco  garagepl  prefarea  
0        0         0      0      0         1         0  
1        0         1      0      0         0         0  
2        0         1      0      0         0         0  
3        1         1      0      0         0         0  
4        0         1      0      0         0         0

In [15]:
x=data2.iloc[:,:-1].values
y=data2.iloc[:,-1:].values.reshape(-1,1)
x,y

(array([[1.00e+00, 4.20e+04, 5.85e+03, ..., 0.00e+00, 0.00e+00, 1.00e+00],
        [2.00e+00, 3.85e+04, 4.00e+03, ..., 0.00e+00, 0.00e+00, 0.00e+00],
        [3.00e+00, 4.95e+04, 3.06e+03, ..., 0.00e+00, 0.00e+00, 0.00e+00],
        ...,
        [5.44e+02, 1.03e+05, 6.00e+03, ..., 0.00e+00, 1.00e+00, 1.00e+00],
        [5.45e+02, 1.05e+05, 6.00e+03, ..., 0.00e+00, 1.00e+00, 1.00e+00],
        [5.46e+02, 1.05e+05, 6.00e+03, ..., 0.00e+00, 1.00e+00, 1.00e+00]]),
 array([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
  

In [16]:
xtrain, xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3, random_state=0)

In [32]:
lr = LogisticRegression()
knn = neighbors.KNeighborsClassifier()
dt = DecisionTreeClassifier()
classifiers=[('A',lr),('B',knn),('C',dt)]

In [38]:
for cf_name, cf in classifiers:
    cf.fit(xtrain,ytrain)
    TResult=cf.predict(xtest)
    TAccuracy=metrics.accuracy_score(ytest,TResult)
    print(TAccuracy)

0.7804878048780488
0.7804878048780488
0.9878048780487805


C:\Users\Administrator\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Administrator\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Administrator\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


In [39]:
VC=VotingClassifier(estimators=classifiers)
VC.fit(xtrain,ytrain)
VResult=VC.predict(xtest)
VAccuracy=metrics.accuracy_score(ytest,VResult)
print(VAccuracy)

0.9146341463414634


C:\Users\Administrator\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Administrator\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Administrator\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
