In [1]:
import tensorflow as tf

In [2]:
hello=tf.constant('Hello, TensorFlow')

In [3]:
sess=tf.Session()

In [4]:
print(sess.run(hello))

b'Hello, TensorFlow'


In [5]:
x1=tf.constant([1,2,3,4])
y1=tf.constant([5,6,7,8])

In [6]:
result=tf.multiply(x1,y1)

In [8]:
print(result)

Tensor("Mul:0", shape=(4,), dtype=int32)


In [9]:
sess.run(result)

array([ 5, 12, 21, 32])

In [11]:
import numpy as np
test1=np.array([1.5,1,5.0,23.0])

In [12]:
test1

array([ 1.5,  1. ,  5. , 23. ])

In [13]:
a=tf.constant(5.0)
b=tf.constant(6.0)
c=a*b

In [14]:
c

<tf.Tensor 'mul_1:0' shape=() dtype=float32>

In [19]:
sess=tf.Session()
output_c=sess.run(c)
writer=tf.summary.FileWriter('./logs',sess.graph)
output_c

30.0

In [17]:
# Placeholder
a1=tf.placeholder(tf.float32)
b1=tf.placeholder(tf.float32)
c1=a1*b1
output_c1=sess.run(c1,{a1:[1,2],b1:[2,4]})
output_c1

array([2., 8.], dtype=float32)

In [18]:
# Variable
d1=tf.Variable([0.8],dtype=tf.float32)
d1

Instructions for updating:
Colocations handled automatically by placer.


<tf.Variable 'Variable:0' shape=(1,) dtype=float32_ref>

In [ ]:
# LinearRegression
