In [18]:
# Logistic Regression

import tensorflow as tf

xdata=[[1,2],[2,1],[2,3],[4,1],[4,4],[5,1],[6,4]]
ydata=[[0],[0],[0],[1],[1],[0],[1]]
# x,y => 0 or 1

In [14]:
X=tf.placeholder(tf.float32, shape=[None,2])
y=tf.placeholder(tf.float32, shape=[None,1])
W=tf.Variable(tf.random_normal([2,1]),name='weight')
b=tf.Variable(tf.random_normal([1]),name='bias')

In [15]:
# Hypothesis sigmoid
hypothesis=tf.sigmoid(tf.matmul(X,W)+b)
cost=-tf.reduce_mean(y*tf.log(hypothesis)+(1-y)*tf.log(1-hypothesis))
train=tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

In [16]:
predicted=tf.cast(hypothesis > 0.5, dtype=tf.float32)
# h >= 0.5 => 1, h < 0.5 => 0
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, y),dtype=tf.float32))

In [21]:
sess=tf.Session()
sess.run(tf.global_variables_initializer())
for s in range(2000):
    cost_val,_=sess.run([cost,train],feed_dict={X:xdata, y:ydata})
    if s % 200 == 0:
        print(s, cost_val)
    h,c,a=sess.run([hypothesis,predicted,accuracy],feed_dict={X:xdata, y:ydata})
    print(h,c,a)

0 0.7397298
[[0.6205182 ]
 [0.3103736 ]
 [0.7541423 ]
 [0.18855684]
 [0.8052424 ]
 [0.1430806 ]
 [0.6809946 ]] [[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.5714286
[[0.62044764]
 [0.3114002 ]
 [0.75445306]
 [0.1903782 ]
 [0.80636704]
 [0.14497846]
 [0.6840833 ]] [[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.5714286
[[0.6203446 ]
 [0.31239298]
 [0.75472087]
 [0.19216834]
 [0.80742717]
 [0.1468536 ]
 [0.6870474 ]] [[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.5714286
[[0.6202104 ]
 [0.313353  ]
 [0.7549476 ]
 [0.19392796]
 [0.80842566]
 [0.14870623]
 [0.6898925 ]] [[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.5714286
[[0.62004626]
 [0.31428134]
 [0.7551348 ]
 [0.19565767]
 [0.8093655 ]
 [0.15053666]
 [0.69262356]] [[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.5714286
[[0.61985344]
 [0.31517905]
 [0.7552843 ]
 [0.19735813]
 [0.81024945]
 [0.15234518]
 [0.6952457 ]] [[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.5714286
[[0.619633  ]
 [0.31604713]
 [0.7553974 ]
 [0.19902998]
 [0.8110798 ]
 [0.15

[[0.51212335]
 [0.34079978]
 [0.66255367]
 [0.32261616]
 [0.77900296]
 [0.31371754]
 [0.7645561 ]] [[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.5714286
[[0.51137257]
 [0.340793  ]
 [0.66180336]
 [0.32318348]
 [0.77859116]
 [0.31455943]
 [0.76459837]] [[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.5714286
[[0.51062375]
 [0.3407858 ]
 [0.6610543 ]
 [0.32374915]
 [0.7781799 ]
 [0.31539947]
 [0.7646402 ]] [[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.5714286
[[0.5098767 ]
 [0.34077817]
 [0.6603065 ]
 [0.32431316]
 [0.7777692 ]
 [0.31623778]
 [0.7646818 ]] [[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.5714286
[[0.50913155]
 [0.34077016]
 [0.65955997]
 [0.32487556]
 [0.7773591 ]
 [0.31707424]
 [0.7647232 ]] [[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.5714286
[[0.5083882 ]
 [0.34076166]
 [0.6588146 ]
 [0.32543626]
 [0.7769496 ]
 [0.31790888]
 [0.7647643 ]] [[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.5714286
[[0.50764674]
 [0.34075278]
 [0.6580705 ]
 [0.32599536]
 [0.7765407 ]
 [0.31874177]
 [0.

[[0.43532833]
 [0.33784333]
 [0.5830067 ]
 [0.37979382]
 [0.7352937 ]
 [0.4015105 ]
 [0.7692614 ]] [[0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.71428573
[[0.43479583]
 [0.33780497]
 [0.58243906]
 [0.3801839 ]
 [0.7349843 ]
 [0.40212807]
 [0.76930374]] [[0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.71428573
[[0.4342649 ]
 [0.3377664 ]
 [0.58187294]
 [0.38057265]
 [0.7346758 ]
 [0.40274373]
 [0.76934606]] [[0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.71428573
[[0.4337357 ]
 [0.3377277 ]
 [0.5813084 ]
 [0.38096002]
 [0.7343684 ]
 [0.40335757]
 [0.76938856]] [[0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.71428573
[[0.43320796]
 [0.33768877]
 [0.58074546]
 [0.38134608]
 [0.7340618 ]
 [0.40396953]
 [0.76943105]] [[0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.71428573
[[0.43268198]
 [0.33764967]
 [0.5801841 ]
 [0.38173082]
 [0.7337562 ]
 [0.40457958]
 [0.7694737 ]] [[0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.71428573
[[0.4321576 ]
 [0.33761042]
 [0.57962435]
 [0.38211426]
 [0.7334514 ]
 [0.40518782

 [0.7749536 ]] [[0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.71428573
[[0.38107237]
 [0.33203465]
 [0.52464366]
 [0.41840085]
 [0.7041494 ]
 [0.46393433]
 [0.77500504]] [[0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.71428573
[[0.38070598]
 [0.33197922]
 [0.52424854]
 [0.4186499 ]
 [0.7039456 ]
 [0.46434715]
 [0.7750564 ]] [[0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.71428573
[[0.38034067]
 [0.33192366]
 [0.52385455]
 [0.418898  ]
 [0.7037425 ]
 [0.46475863]
 [0.7751079 ]] [[0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.71428573
[[0.3799764 ]
 [0.33186802]
 [0.5234618 ]
 [0.41914514]
 [0.70354015]
 [0.46516865]
 [0.77515954]] [[0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.71428573
[[0.37961328]
 [0.3318123 ]
 [0.52307034]
 [0.4193912 ]
 [0.70333856]
 [0.46557716]
 [0.77521116]] [[0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.71428573
[[0.37925127]
 [0.33175644]
 [0.52268   ]
 [0.41963643]
 [0.7031378 ]
 [0.46598428]
 [0.77526283]] [[0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]] 0.71428573
[[0.3788903 ]

 [0.78226924]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.3403778 ]
 [0.32384974]
 [0.48122552]
 [0.44418794]
 [0.68294114]
 [0.50794786]
 [0.7823263 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.34012812]
 [0.32378408]
 [0.48096418]
 [0.4443307 ]
 [0.6828237 ]
 [0.5082021 ]
 [0.7823834 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.33987913]
 [0.32371843]
 [0.48070368]
 [0.4444728 ]
 [0.6827067 ]
 [0.50845534]
 [0.7824405 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.33963078]
 [0.32365268]
 [0.4804439 ]
 [0.4446143 ]
 [0.6825903 ]
 [0.5087077 ]
 [0.78249764]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.33938316]
 [0.3235869 ]
 [0.48018494]
 [0.4447551 ]
 [0.6824744 ]
 [0.50895905]
 [0.78255486]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.33913612]
 [0.32352105]
 [0.4799268 ]
 [0.44489536]
 [0.682359  ]
 [0.5092095 ]
 [0.782612  ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.33888975]

[[0.3143926 ]
 [0.31561074]
 [0.4546593 ]
 [0.45746025]
 [0.67209184]
 [0.53274095]
 [0.7893658 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.31420842]
 [0.31554073]
 [0.45447674]
 [0.45754075]
 [0.6720269 ]
 [0.5329024 ]
 [0.7894247 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.3140247 ]
 [0.31547073]
 [0.4542946 ]
 [0.4576209 ]
 [0.6719623 ]
 [0.5330633 ]
 [0.7894835 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.31384137]
 [0.31540072]
 [0.454113  ]
 [0.45770058]
 [0.6718981 ]
 [0.53322357]
 [0.78954244]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.31365848]
 [0.31533065]
 [0.45393196]
 [0.4577799 ]
 [0.67183435]
 [0.5333832 ]
 [0.78960127]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.313476  ]
 [0.3152606 ]
 [0.4537514 ]
 [0.45785877]
 [0.6717708 ]
 [0.5335422 ]
 [0.7896601 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.313294  ]
 [0.31519046]
 [0.45357135]
 [0.45793724]
 [0.67170763]
 [0.5337006 

[[0.2951067 ]
 [0.3071771 ]
 [0.43613443]
 [0.46452314]
 [0.6665407 ]
 [0.5482136 ]
 [0.796374  ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.29496413]
 [0.30710572]
 [0.43600258]
 [0.46456385]
 [0.6665102 ]
 [0.54831594]
 [0.7964327 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.2948219 ]
 [0.3070343 ]
 [0.43587112]
 [0.4646043 ]
 [0.66647995]
 [0.5484179 ]
 [0.79649144]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.2946799 ]
 [0.3069629 ]
 [0.43573996]
 [0.46464443]
 [0.66644996]
 [0.54851943]
 [0.79655004]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.29453823]
 [0.3068915 ]
 [0.4356092 ]
 [0.46468434]
 [0.66642016]
 [0.5486206 ]
 [0.79660875]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.2943968 ]
 [0.30682012]
 [0.43547875]
 [0.46472397]
 [0.66639066]
 [0.5487213 ]
 [0.7966674 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.29425564]
 [0.3067487 ]
 [0.43534863]
 [0.46476337]
 [0.6663612 ]
 [0.54882175

[[0.27987808]
 [0.29868886]
 [0.422561  ]
 [0.46773624]
 [0.6643378 ]
 [0.55796885]
 [0.8032923 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.27976307]
 [0.2986178 ]
 [0.4224626 ]
 [0.46775115]
 [0.6643298 ]
 [0.5580329 ]
 [0.8033498 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.27964824]
 [0.2985468 ]
 [0.42236453]
 [0.46776596]
 [0.664322  ]
 [0.5580967 ]
 [0.8034072 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.27953362]
 [0.29847577]
 [0.4222667 ]
 [0.46778056]
 [0.6643143 ]
 [0.5581602 ]
 [0.80346465]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.27941918]
 [0.29840478]
 [0.422169  ]
 [0.46779507]
 [0.6643069 ]
 [0.55822355]
 [0.803522  ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.27930495]
 [0.2983338 ]
 [0.4220716 ]
 [0.46780938]
 [0.6642995 ]
 [0.55828655]
 [0.8035794 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.2791909 ]
 [0.29826283]
 [0.4219744 ]
 [0.46782348]
 [0.6642922 ]
 [0.5583493 

[[0.26603088]
 [0.289343  ]
 [0.41121268]
 [0.46844208]
 [0.66441566]
 [0.5645599 ]
 [0.8107993 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.26593643]
 [0.28927368]
 [0.4111387 ]
 [0.46843916]
 [0.6644236 ]
 [0.56459695]
 [0.8108546 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.26584202]
 [0.28920436]
 [0.4110649 ]
 [0.46843606]
 [0.6644316 ]
 [0.5646338 ]
 [0.8109099 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.2657478 ]
 [0.28913504]
 [0.4109912 ]
 [0.46843287]
 [0.6644397 ]
 [0.5646705 ]
 [0.8109653 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.26565367]
 [0.28906575]
 [0.41091776]
 [0.46842954]
 [0.6644479 ]
 [0.5647071 ]
 [0.8110205 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.26555967]
 [0.2889965 ]
 [0.41084433]
 [0.4684262 ]
 [0.6644562 ]
 [0.5647435 ]
 [0.8110758 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.2654658 ]
 [0.28892723]
 [0.41077107]
 [0.46842268]
 [0.6644646 ]
 [0.56477976

 [0.8173112 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.25540772]
 [0.28108165]
 [0.4031908 ]
 [0.46743578]
 [0.66595155]
 [0.56804734]
 [0.81736434]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.255326  ]
 [0.28101453]
 [0.40313137]
 [0.4674228 ]
 [0.66596836]
 [0.568069  ]
 [0.8174175 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.2552444 ]
 [0.28094742]
 [0.40307197]
 [0.46740982]
 [0.6659853 ]
 [0.56809056]
 [0.8174706 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.25516284]
 [0.2808803 ]
 [0.40301272]
 [0.4673967 ]
 [0.6660022 ]
 [0.56811196]
 [0.81752366]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.25508136]
 [0.28081325]
 [0.40295354]
 [0.4673836 ]
 [0.6660192 ]
 [0.56813323]
 [0.81757665]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.255     ]
 [0.2807462 ]
 [0.4028945 ]
 [0.4673704 ]
 [0.6660363 ]
 [0.56815445]
 [0.81762975]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.25491872]

 [0.8236005 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.24610128]
 [0.27310935]
 [0.3966248 ]
 [0.46547344]
 [0.6683444 ]
 [0.5700273 ]
 [0.82365125]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.24602881]
 [0.2730448 ]
 [0.39657515]
 [0.46545443]
 [0.6683667 ]
 [0.57003903]
 [0.82370204]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.24595632]
 [0.2729802 ]
 [0.39652565]
 [0.46543533]
 [0.66838896]
 [0.5700508 ]
 [0.82375276]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.24588394]
 [0.27291563]
 [0.39647615]
 [0.46541622]
 [0.66841143]
 [0.57006234]
 [0.82380354]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.24581169]
 [0.27285114]
 [0.3964268 ]
 [0.46539712]
 [0.66843385]
 [0.5700739 ]
 [0.8238542 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.24573947]
 [0.27278665]
 [0.3963774 ]
 [0.46537796]
 [0.6684563 ]
 [0.5700854 ]
 [0.82390493]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.24566728]

[[0.23750024]
 [0.2652062 ]
 [0.39088473]
 [0.4628455 ]
 [0.6713591 ]
 [0.5710662 ]
 [0.8298449 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.23743486]
 [0.26514435]
 [0.3908421 ]
 [0.46282282]
 [0.6713848 ]
 [0.57107145]
 [0.82989323]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.23736951]
 [0.26508257]
 [0.39079952]
 [0.46280015]
 [0.67141044]
 [0.5710768 ]
 [0.8299415 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.23730424]
 [0.26502082]
 [0.39075705]
 [0.46277738]
 [0.67143613]
 [0.57108206]
 [0.8299898 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.237239  ]
 [0.26495904]
 [0.39071456]
 [0.4627546 ]
 [0.67146176]
 [0.5710872 ]
 [0.8300381 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.23717381]
 [0.2648973 ]
 [0.39067212]
 [0.46273184]
 [0.67148757]
 [0.57109237]
 [0.8300863 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.23710868]
 [0.26483563]
 [0.3906298 ]
 [0.46270907]
 [0.67151326]
 [0.5710975 

 [0.8355962 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.22980009]
 [0.2577695 ]
 [0.385955  ]
 [0.45992243]
 [0.674633  ]
 [0.57146114]
 [0.83564216]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.22974008]
 [0.25771043]
 [0.3859172 ]
 [0.45989782]
 [0.6746604 ]
 [0.5714625 ]
 [0.8356881 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.22968015]
 [0.2576514 ]
 [0.38587943]
 [0.4598732 ]
 [0.67468786]
 [0.5714638 ]
 [0.835734  ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.22962026]
 [0.25759235]
 [0.38584173]
 [0.45984855]
 [0.6747153 ]
 [0.57146513]
 [0.83577985]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.22956038]
 [0.25753334]
 [0.38580403]
 [0.45982385]
 [0.6747427 ]
 [0.5714665 ]
 [0.83582574]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.22950056]
 [0.25747436]
 [0.38576642]
 [0.4597992 ]
 [0.6747702 ]
 [0.57146776]
 [0.83587164]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.22944072]

[[0.22275217]
 [0.250725  ]
 [0.38156572]
 [0.45685565]
 [0.67803466]
 [0.57147294]
 [0.84110814]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.22269648]
 [0.2506686 ]
 [0.38153145]
 [0.4568301 ]
 [0.6780629 ]
 [0.57147187]
 [0.8411518 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.22264089]
 [0.25061223]
 [0.38149709]
 [0.4568046 ]
 [0.67809117]
 [0.5714709 ]
 [0.84119546]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.22258526]
 [0.25055584]
 [0.38146284]
 [0.4567791 ]
 [0.67811936]
 [0.57146984]
 [0.8412391 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.22252971]
 [0.25049952]
 [0.3814286 ]
 [0.45675352]
 [0.6781476 ]
 [0.57146883]
 [0.84128267]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.22247419]
 [0.25044322]
 [0.3813944 ]
 [0.45672798]
 [0.6781759 ]
 [0.5714677 ]
 [0.84132624]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.22241868]
 [0.25038692]
 [0.3813602 ]
 [0.45670244]
 [0.6782041 ]
 [0.5714666 

[[0.21597669]
 [0.2437873 ]
 [0.37741512]
 [0.453621  ]
 [0.68161154]
 [0.5712461 ]
 [0.8464679 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.21592472]
 [0.24373358]
 [0.37738344]
 [0.4535952 ]
 [0.68163997]
 [0.57124364]
 [0.84650934]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.2158728 ]
 [0.24367988]
 [0.3773518 ]
 [0.45356947]
 [0.68166834]
 [0.57124114]
 [0.8465507 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.21582091]
 [0.24362622]
 [0.37732017]
 [0.45354378]
 [0.6816969 ]
 [0.5712387 ]
 [0.8465921 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.21576901]
 [0.24357253]
 [0.37728855]
 [0.45351803]
 [0.6817253 ]
 [0.5712362 ]
 [0.8466335 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.21571714]
 [0.24351892]
 [0.37725696]
 [0.45349228]
 [0.68175375]
 [0.5712337 ]
 [0.84667486]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.21566533]
 [0.24346529]
 [0.37722537]
 [0.4534665 ]
 [0.6817821 ]
 [0.5712311 

[[0.2094858 ]
 [0.23702627]
 [0.37346852]
 [0.45031074]
 [0.68527395]
 [0.5708705 ]
 [0.85166925]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.20943707]
 [0.23697513]
 [0.37343892]
 [0.4502852 ]
 [0.68530214]
 [0.5708672 ]
 [0.8517085 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.20938835]
 [0.23692405]
 [0.37340933]
 [0.4502597 ]
 [0.68533033]
 [0.57086384]
 [0.85174763]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.20933966]
 [0.23687303]
 [0.3733798 ]
 [0.4502342 ]
 [0.6853587 ]
 [0.5708607 ]
 [0.85178685]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.20929101]
 [0.23682196]
 [0.37335023]
 [0.45020863]
 [0.6853869 ]
 [0.57085735]
 [0.851826  ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.20924239]
 [0.23677094]
 [0.37332073]
 [0.45018312]
 [0.68541527]
 [0.570854  ]
 [0.8518651 ]] [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 0.71428573
[[0.20919377]
 [0.23671992]
 [0.37329116]
 [0.4501576 ]
 [0.6854434 ]
 [0.57085073