In [20]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

b=np.array([[1,2],[3,4]])
print(b)

c=np.array([1,2,3,4], ndmin=2)
print(c)

d=np.array([1,2,3,4], dtype=complex)
print(d)

[1 2 3 4]
[[1 2]
 [3 4]]
[[1 2 3 4]]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [11]:
import numpy as np
dt=np.dtype(np.int32)
print(dt)
type(dt)

int32


numpy.dtype

In [16]:
import numpy as np
dt=np.dtype([('age',np.int8)])

a = np.array([10,20,30], dtype=np.int8)
print(a)

[10 20 30]


In [21]:
import numpy as np
a=np.array([1,2,3])
print(a.shape)
a1=np.array([[1,2,3],[4,5,6]])
print(a1.shape)

(3,)
(2, 3)


In [37]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
print(a)
print(a.shape)
print(a.ndim)
a1=np.array((1,2,3,4))
print(a1)
a2=np.array(((1,2),(3,4)))
print(a2)
print(a2.ndim)
print(type(a2))

#for i in range(14):
 #   print(i)
a3=np.arange(24)
print(a3.ndim)
a3.shape=(2,4,3)
print(a3)
a4=np.arange(24)
a5=a4.reshape(2,4,3)
print(a5.ndim)
print(a5)
print(a4.ndim)

[1 2 3 4 5 6 7 8]
(8,)
1
[1 2 3 4]
[[1 2]
 [3 4]]
2
<class 'numpy.ndarray'>
1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
3
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
1


In [45]:
import numpy as np
a=np.zeros((3,3))
print(a)
print(a.dtype)
a1=np.ones((2,2))
print(a1)
a2=np.empty((4,4))
print(a2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64
[[1. 1.]
 [1. 1.]]
[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.29061074e-306]
 [1.69119873e-306 1.78019082e-306 1.89146896e-307 1.37961302e-306]
 [1.05699242e-307 8.01097889e-307 2.22523004e-306 1.37961709e-306]
 [1.69118787e-306 1.86921822e-306 1.37962320e-306 1.69121231e-306]]


In [55]:
import numpy as np
a=np.array([1,2,3,4,5,6], dtype=np.int8)
print(a.ndim)
print(a.dtype)
print(a.shape)

a1=np.array([1,2,3,4], dtype=np.float)
print(a1.ndim)
print(a1.dtype)
print(a1.shape)

a2=a1.astype(np.int16)
print(a2)
print(a2.dtype)

#1차원 0으로 채우기
a3=np.zeros(5)
print(a3)
#1차원 0으로 채우고 int 정의하기
a4=np.zeros((5,),dtype=np.int)
print(a4)
print(a4.dtype)

1
int8
(6,)
1
float64
(4,)
[1 2 3 4]
int16
[0. 0. 0. 0. 0.]
[0 0 0 0 0]
int32
